version: '3.8'

services:

  db:
    container_name: db
    image: postgres
    ports:
      - 5432:5432
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    volumes:
      - ./db/postgres_data:/var/lib/postgresql/data
      - ./db/create_schema.sql:/docker-entrypoint-initdb.d/create_schema.sql

  api:
    container_name: api
    build: ./queryforgeapi
    env_file:
      - .env
    ports:
      - "8080:8080"
    depends_on:
      - db

  view:
    container_name: view
    build: ./queryforgeview
    ports:
      - "9000:3000"
    environment:
      - NODE_ENV=production
    volumes:
      - ./queryforgeview:/app
    depends_on:
      - api
