version: '3.8'

services:

  db:
    image: postgres
    restart: always
    container_name: my-postgres-container
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    volumes:
      - ./db/postgres_data:/var/lib/postgresql/data
      - ./db/create_schema.sql:/docker-entrypoint-initdb.d/create_schema.sql
    ports:
      - "9091:5432"

#  backend:
#    build:
#      context: ./path-to-your-backend
#      dockerfile: Dockerfile
#    ports:
#      - "8080:8080"
#    environment:
#      SPRING_DATASOURCE_URL: 
#      SPRING_DATASOURCE_USERNAME: 
#      SPRING_DATASOURCE_PASSWORD: 
#    depends_on:
#      - db

#  frontend:
#    build:
#      context: ./path-to-your-frontend
#      dockerfile: Dockerfile
#    ports:
#      - "3000:80"